const app=document.querySelector('#app');let token=localStorage.getItem('brd_inf_admin');
const api=(action,opts={})=>fetch('/api/index?action='+action,{...opts,headers:{...(opts.headers||{}),...(token?{Authorization:'Bearer '+token}:{})}});
function shell(content){app.innerHTML=`<header><div class="wrap top"><div class="brand"><img src="/admin/influencers/logo.jpeg"><span>BRANDIRASCK<small>INFLUENCERS ADMIN</small></span></div>${token?'<button class="btn" id="logout">Logout</button>':''}</div></header><main class="wrap">${content}</main>`;document.querySelector('#logout')?.addEventListener('click',()=>{localStorage.removeItem('brd_inf_admin');token=null;renderLogin()})}
function renderLogin(){shell(`<div class="login"><div class="eyebrow">PRIVATE ADMIN</div><h1>Influencers Admin</h1><p class="notice">هذا الـAdmin مستقل عن باقي مواقع BRANDIRASCK.</p><div class="field"><label>Username</label><input id="u"></div><div class="field"><label>Password</label><input id="p" type="password"></div><button class="btn" id="login">دخول</button></div>`);document.querySelector('#login').onclick=login}
async function login(){const r=await api('admin-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:u.value,password:p.value})});const j=await r.json();if(!r.ok)return alert('بيانات الدخول غير صحيحة');token=j.token;localStorage.setItem('brd_inf_admin',token);renderDash()}
async function renderDash(){const [c,t]=await Promise.all([api('admin-codes'),api('admin-temp')]);if(c.status===401){token=null;localStorage.removeItem('brd_inf_admin');return renderLogin()}const cj=await c.json(),tj=await t.json();shell(`<div class="dashboard"><div class="eyebrow">CONTROL CENTER</div><h1>Influencers Dashboard</h1><p class="notice">الـPDF والتسجيلات غير المعتمدة مؤقتة فقط. من بعد انتهاء 30 دقيقة يتم حذفها تلقائياً.</p><div class="stats"><div class="stat"><b>${cj.items.filter(x=>x.status==='ACTIVE').length}</b>Codes Active</div><div class="stat"><b>${cj.items.filter(x=>x.status==='USED').length}</b>Codes Used</div><div class="stat"><b>${tj.items.length}</b>Temporary Registrations</div><div class="stat"><b>30m</b>PDF Retention</div></div><section class="section"><div class="row"><h2>Registration Codes</h2><button class="btn" id="gen">Generate Code</button></div><div id="codes">${cj.items.map(x=>`<div class="row"><span class="code">${x.id.slice(0,8)}…</span><span class="badge">${x.status}</span><small>${new Date(x.created_at).toLocaleString('fr-MA')}</small></div>`).join('')}</div></section><section class="section"><h2>Temporary Registrations</h2><div id="temps">${tj.items.map(x=>`<div class="card"><b>${x.payload?.name||'Unknown'}</b><p class="notice">${x.payload?.nickname||''} · ${x.payload?.city||''}</p><div class="actions">${x.has_pdf?`<a class="btn ghost pdf" href="/api/index?action=admin-pdf&id=${x.id}" target="_blank">View PDF</a>`:''}<button class="btn" data-approve="${x.id}">Approve → Catalog</button></div></div>`).join('')||'<p class="notice">لا توجد تسجيلات مؤقتة حالياً.</p>'}</div></section></div>`);document.querySelector('#gen').onclick=generate;document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>approve(b.dataset.approve))}
async function generate(){const r=await api('admin-generate-code',{method:'POST'}),j=await r.json();if(!r.ok)return alert(j.error);alert('Registration Code: '+j.code+'\nصالح لمدة 30 دقيقة.');renderDash()}
async function approve(id){const r=await api('admin-approve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const j=await r.json();if(!r.ok)return alert(j.error);alert('تم اعتماد Influencer وإضافته للـCatalog.');renderDash()}
if(token)renderDash();else renderLogin();
